Cache Prometheus
GarnerCorp/build-actions pull request #8
Opened 2023-04-04 12:35 UTC by drozd-A

2023-05-02 19:50 UTC, danielperev requested changes

2023-05-02 19:50 UTC, danielperev commented on scala/action.yml
> +      run: ${{ inputs.build-script || $GITHUB_ACTION_PATH/build-scala-ci.sh }} ${{ inputs.build-script-args }}
1. if `build-script` is set then use `build-script-args` (because if you provide your own script you should provide your own arguments)
2. if `build-script` is not set then try to use `build-script-args` with `$GITHUB_ACTION_PATH/build-scala-ci.sh` 
3. otherwise use default args `${{ github.event.pull_request.number || github.ref_name }}` with `$GITHUB_ACTION_PATH/build-scala-ci.sh`

2023-05-02 19:50 UTC, danielperev commented on scala/action.yml
> +      run: '"${{ inputs.build-script || $GITHUB_ACTION_PATH/build-scala-ci.sh }}" ${{ inputs.build-script-args }}'
belongs in previous commit

2023-07-12 14:21 UTC, jsoref approved these changes

2023-07-12 14:23 UTC, merged